### ISSUE TITLE
IsFormatSampleRateAndChannelCountValid CRASH

### ISSUE THREAD

**Issue by fukemy** [vlider/Mic-recording-minimal-example#4]
hi, i got this crash
```
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: IsFormatSampleRateAndChannelCountValid(format)'
terminating with uncaught exception of type NSException
CoreSimulator 732.18.6 - Device: iPhone 11 (2CB1AA39-8983-4078-8A87-6F2058AF84DB) - Runtime: iOS 14.4 (18D46) - DeviceType: iPhone 11
```
'
can u help?

**Comment by vlider** [comment]
I haven’t updated this code for quite long period of time, assume something
has changed in api.
Could you check Apple docs to see an example of initializing audio engine?
Also found this via quick search:
https://stackoverflow.com/questions/60984704/required-condition-is-false-isformatsamplerateandchannelcountvalidformat

Also, I see that you are running in simulator - try on device.

Hope this helps

**Comment by fukemy** [comment]
Solved thanks
